#!/usr/bin/env python3
"""Emit one Odocrypt epoch's constants as SystemVerilog.

Odocrypt regenerates its S-boxes, permutation masks and rotations from a key
that changes every ~10 days. For any one epoch they are COMPILE-TIME CONSTANTS,
which is the whole reason the algorithm suits an FPGA: rotations and word
shuffles become wiring, masks become constant AND/XOR, and the S-boxes become
ROM. A fresh bitstream every 10 days is the intended cost of entry.

The tables here are random permutations from a fixed seed. Their *contents* are
not what is being measured -- their shape is -- but they must be permutations,
as the real key schedule produces, and they must be random rather than
structured or synthesis will optimise away work a real epoch would demand.
"""
import random
import sys

SMALL_W, LARGE_W = 6, 10
STATE_SIZE = 10
SMALL_COUNT = 40          # DIGEST_BITS / (SMALL_W + LARGE_W)
LARGE_COUNT = STATE_SIZE
PBOX_SUBROUNDS = 6
ROTATION_COUNT = 6

rng = random.Random(0xD16B17E)


def perm(n):
    v = list(range(n))
    rng.shuffle(v)
    return v


def main() -> int:
    out = []
    w = out.append
    w("// GENERATED by gen_tables.py -- one Odocrypt epoch's constants.")
    w("// Do not edit; regenerate for a different epoch.")
    w("")
    w("localparam int SMALL_W = %d;" % SMALL_W)
    w("localparam int LARGE_W = %d;" % LARGE_W)
    w("localparam int STATE_SIZE = %d;" % STATE_SIZE)
    w("localparam int SMALL_COUNT = %d;" % SMALL_COUNT)
    w("localparam int LARGE_COUNT = %d;" % LARGE_COUNT)
    w("")

    # 6-bit S-boxes: 40 permutations of 0..63. One LUT6 per output bit.
    w("localparam logic [5:0] SBOX1 [0:%d][0:63] = '{" % (SMALL_COUNT - 1))
    for i in range(SMALL_COUNT):
        p = perm(64)
        body = ", ".join("6'd%d" % v for v in p)
        w("  '{%s}%s" % (body, "," if i < SMALL_COUNT - 1 else ""))
    w("};")
    w("")

    # 10-bit S-boxes: 10 permutations of 0..1023. Block RAM sized.
    w("localparam logic [9:0] SBOX2 [0:%d][0:1023] = '{" % (LARGE_COUNT - 1))
    for i in range(LARGE_COUNT):
        p = perm(1024)
        chunks = []
        for k in range(0, 1024, 16):
            chunks.append("    " + ", ".join("10'd%d" % v for v in p[k:k + 16]))
        w("  '{")
        w(",\n".join(chunks))
        w("  }%s" % ("," if i < LARGE_COUNT - 1 else ""))
    w("};")
    w("")

    # Pbox masks: [2 permutations][PBOX_SUBROUNDS][STATE_SIZE/2] of 64 bits
    w("localparam logic [63:0] PMASK [0:1][0:%d][0:%d] = '{" % (PBOX_SUBROUNDS - 1, STATE_SIZE // 2 - 1))
    for p_ in range(2):
        w("  '{")
        rows = []
        for s in range(PBOX_SUBROUNDS):
            vals = ", ".join("64'h%016x" % rng.getrandbits(64) for _ in range(STATE_SIZE // 2))
            rows.append("    '{%s}" % vals)
        w(",\n".join(rows))
        w("  }%s" % ("," if p_ == 0 else ""))
    w("};")
    w("")

    # Pbox rotations: [2][PBOX_SUBROUNDS-1][STATE_SIZE/2], 0..63
    w("localparam int PROT [0:1][0:%d][0:%d] = '{" % (PBOX_SUBROUNDS - 2, STATE_SIZE // 2 - 1))
    for p_ in range(2):
        w("  '{")
        rows = []
        for s in range(PBOX_SUBROUNDS - 1):
            vals = ", ".join(str(rng.randrange(64)) for _ in range(STATE_SIZE // 2))
            rows.append("    '{%s}" % vals)
        w(",\n".join(rows))
        w("  }%s" % ("," if p_ == 0 else ""))
    w("};")
    w("")

    # Linear-mix rotations and this round's key.
    w("localparam int ROTS [0:%d] = '{%s};"
      % (ROTATION_COUNT - 1, ", ".join(str(rng.randrange(1, 64)) for _ in range(ROTATION_COUNT))))
    w("localparam logic [15:0] ROUNDKEY = 16'h%04x;" % rng.getrandbits(16))
    w("")

    path = "rtl/odo_tables.svh"
    with open(path, "w", newline="\n") as fh:
        fh.write("\n".join(out) + "\n")
    print("wrote %s (%d lines)" % (path, len(out)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
